#page title
page_title                                : 복실이 - 캡스톤 11팀                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : 복실이                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : 나만의 작은 복지사                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : 부모님의 건강정보가 궁금하시지 않으신가요? <br>부모님의 건강 상태를 모니터링하고 건강한 삶을 유지하는데 필요한 다양한 정보와 조언을 제공합니다. <br>복실이를 통해 부모님의 건강을 보다 적극적으로 관리해보세요!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Emil Baehr                                
your_link                                 : https://emilbaehr.com                     
your_city                                 : Copenhagen                                
email_address                             : emil.baehr@gmail.com
facebook_username                         :                                           
instagram_username                        : ebaehr
twitter_username                          : ebaehr
github_username                           : emilbaehr
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : 건강 데이터 분석
    description                           : 영양소 및 운동 정보, 복용중인 약 정보를 통해, 건강 분석을 받아볼 수 있습니다.
    fontawesome_icon_name                 : notes-medical
  
  - title                                 : 간단한 식단 등록
    description                           : 이미지 인식을 활용하여 사진 한장으로 자신이 식단을 간편하게 등록할 수 있습니다.
    fontawesome_icon_name                 : mortar-pestle

  - title                                 : 간편하게 관리하는 내 약
    description                           : OCR기술을 활용하여 처방약부터 시판약까지 한눈에 관리가 가능합니다.
    fontawesome_icon_name                 : capsules

  - title                                 : AI 복지사의 건강 피드백
    description                           : 분석된 데이터를 통하여 AI 복지사의 개인 맞춤형 조언을 얻을 수 있습니다.
    fontawesome_icon_name                 : message-medical

  - title                                 : 실시간으로 확인하는 부모님의 건강 정보
    description                           : 등록된 보호자라면, 언제 어디서든 부모님의 건강 정보를 확인할 수 있습니다.
    fontawesome_icon_name                 : display-medical

  - title                                 : 3-Way 하이브리드 플랫폼
    description                           : IOS, Android, Web을 모두 지원하여, 앱 설치가 어려운 분들도 웹 링크를 통해 이용가능합니다.
    fontawesome_icon_name                 : display-medical    



team_info                                 :
  - name                                  : 김호준(XXXX1604)
    description                           : Backend
    fontawesome_icon_name                 : heart-pulse
  - name                                  : 김호준(XXXX1604)
    description                           : Backend
    fontawesome_icon_name                 : heart-pulse
  - name                                  : 김호준(XXXX1604)
    description                           : Backend
    fontawesome_icon_name                 : heart-pulse
  - name                                  : 김호준(XXXX1604)
    description                           : Backend
    fontawesome_icon_name                 : heart-pulse
  - name                                  : 김호준(XXXX1604)
    description                           : Backend
    fontawesome_icon_name                 : heart-pulse

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
